[package]
name = "ffmpeg-encoder"
version = "0.0.0"
edition.workspace = true
readme = "README.md"

[features]
default = []
build = ["ffmpeg/build"]

[dependencies]
ffmpeg = { workspace = true, features = ["avformat", "swscale", "swresample"] }
libc = "0.2"
