name: Bug report
description: Create a bug report
labels: ["bug"]
assignees: []
body:
  - type: dropdown
    id: os
    attributes:
      label: Operating system
      description: Which OS are you using?
      options:
        - Windows
        - macOS
        - Linux + Flatpak
        - Linux
        - Other Unix-like
      multiple: false
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: What happened, and what did you expect?
    validations:
      required: true
