name: Windows
description: Build Windows builds

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: powershell
      run: |
        mkdir ffmpeg
        ls
        cd ffmpeg
        $VCINSTALLDIR = $(& "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath)
        Add-Content $env:GITHUB_ENV "LIBCLANG_PATH=${VCINSTALLDIR}\VC\Tools\LLVM\x64\bin`n"
        Invoke-WebRequest "${env:FFMPEG_DOWNLOAD_URL}" -OutFile ffmpeg-release-full-shared.7z
        ls
        7z x ffmpeg-release-full-shared.7z
        mv ffmpeg-*/* ./
        ls
        cd ..
        Add-Content $env:GITHUB_ENV "FFMPEG_DIR=${pwd}\ffmpeg`n"
        Add-Content $env:GITHUB_PATH "${pwd}\ffmpeg\bin`n"

    - uses: Swatinem/rust-cache@v2
    - uses: dtolnay/rust-toolchain@stable
    - name: Build Ubuntu Release
      shell: bash
      run: cargo build --release -p neothesia-cli
    - uses: actions/upload-artifact@v4
      with:
        name: windows-recorder-artifact
        path: target/release/neothesia-cli.exe
