[package]
name = "iced_widget"
description = "The built-in widgets for iced"
edition = "2021"

[features]

[dependencies]
iced_core.workspace = true
iced_graphics.workspace = true
iced_wgpu.workspace = true

num-traits.workspace = true
log.workspace = true
unicode-segmentation.workspace = true
