name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: Build
        uses: ./.github/actions/ubuntu
      - name: ls
        run: ls -l app.zip
      - name: Rename
        run: mv app.zip neothesia-ubuntu.zip
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{github.ref_name}} neothesia-ubuntu.zip

  build_ubuntu_recorder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: Build
        uses: ./.github/actions/ubuntu-recorder
      - name: ls
        run: ls -l app.zip
      - name: Rename
        run: mv app.zip neothesia-cli-ubuntu.zip
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_FLAGS: --features build-ffmpeg
        run: gh release upload ${{github.ref_name}} neothesia-cli-ubuntu.zip

  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - id: Build
        uses: ./.github/actions/windows
      - name: ls
        run: ls -l target/release/neothesia.exe
      - name: Rename
        run: Move-Item -Path target/release/neothesia.exe -Destination neothesia.exe
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{github.ref_name}} neothesia.exe

  build_windows_recorder:
    runs-on: windows-latest

    env:
      FFMPEG_DOWNLOAD_URL: https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full-shared.7z
      
    steps:
      - uses: actions/checkout@v4
      - id: Build
        uses: ./.github/actions/windows-recorder
      - name: ls
        run: ls -l target/release/neothesia-cli.exe
      - name: Rename
        run: Move-Item -Path target/release/neothesia-cli.exe -Destination neothesia-cli.exe
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{github.ref_name}} neothesia-cli.exe

  build_macos:
    runs-on: macos-latest

    env:
      MACOSX_DEPLOYMENT_TARGET: 10.12

    steps:
      - uses: actions/checkout@v4
      - id: Build
        uses: ./.github/actions/macos
      - name: ls
        run: ls -l .github/app/app.zip
      - name: Rename
        run: mv .github/app/app.zip neothesia-macos.zip
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{github.ref_name}} neothesia-macos.zip

